# Site settings
title: "Prateek Sunal's Resume"
description: "A resume for Prateek Sunal"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Prateek Sunal"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "prateek@sunal.in"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91-6395444509"
resume_contact_address:         "Uttarakhand, India"

resume_header_contact_info:     "Uttarakhand, India • +91-6395444509 • prateek@sunal.in"
display_header_contact_info:    "false"
# This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise
resume_header_intro: "<p>I'm a software engineer with a passion for building beautiful digital experiences. I've spent the last 4 years working in the App development industry, where I've gained experience in the full software development lifecycle, from initial concept to final delivery. I'm currently focused on App development, Back-end web development and CLI development using Rust.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/prateekmedia"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/prateeksunal"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://prateek.sunal.in"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
